import { Resend } from "resend";
import { clerkClient } from "@clerk/nextjs/server";
import type { PipelineSpec, PipelineRunOutput } from "./types";

let resendClient: Resend | null = null;
function getResend(): Resend {
  if (!process.env.RESEND_API_KEY) {
    throw new Error("RESEND_API_KEY is not set");
  }
  if (!resendClient) {
    resendClient = new Resend(process.env.RESEND_API_KEY);
  }
  return resendClient;
}

const FROM = process.env.RESEND_FROM ?? "Trove <onboarding@resend.dev>";

export async function sendPipelineEmail(
  userId: string,
  spec: PipelineSpec,
  output: PipelineRunOutput
): Promise<void> {
  const resend = getResend();

  const client = await clerkClient();
  const user = await client.users.getUser(userId);
  const email = user.primaryEmailAddress?.emailAddress;
  if (!email) {
    throw new Error("user has no primary email address");
  }

  const html = renderHtml(spec, output);
  const text = renderText(spec, output);

  const result = await resend.emails.send({
    from: FROM,
    to: email,
    subject: spec.name,
    html,
    text,
  });

  if (result.error) {
    throw new Error(`resend: ${result.error.message}`);
  }
}

function renderHtml(spec: PipelineSpec, output: PipelineRunOutput): string {
  const body = renderBodyHtml(output);
  return `<!doctype html>
<html>
<body style="margin:0;padding:0;background:#fafafa;font-family:-apple-system,BlinkMacSystemFont,system-ui,sans-serif;color:#1a1a1a;">
  <div style="max-width:600px;margin:0 auto;padding:32px 24px;">
    <div style="font-size:11px;letter-spacing:0.12em;text-transform:uppercase;color:#999;margin-bottom:8px;">From Trove</div>
    <h1 style="font-size:20px;font-weight:600;margin:0 0 16px 0;line-height:1.3;">${escapeHtml(spec.name)}</h1>
    ${body}
    <hr style="border:none;border-top:1px solid #e5e5e5;margin:32px 0 16px 0;">
    <div style="font-size:11px;color:#999;">Generated by your Trove pipeline. View in app: <a href="https://trove-pearl.vercel.app/pipelines" style="color:#666;">pipelines</a>.</div>
  </div>
</body>
</html>`;
}

function renderBodyHtml(output: PipelineRunOutput): string {
  const forgotten = output.forgotten
    ? `<div style="margin-top:24px;padding-top:16px;border-top:1px solid #e5e5e5;">
  <div style="font-size:11px;letter-spacing:0.1em;text-transform:uppercase;color:#b45309;margin-bottom:6px;">Forgotten</div>
  <p style="font-size:15px;font-style:italic;color:#1a1a1a;margin:0 0 4px 0;">${escapeHtml(output.forgotten.title ?? "(untitled)")}</p>
  ${output.forgotten.summary ? `<p style="font-size:13px;color:#666;margin:0;">${escapeHtml(output.forgotten.summary)}</p>` : ""}
</div>`
    : "";

  if (output.shape === "text") {
    return `<p style="font-size:15px;line-height:1.6;color:#333;">${escapeHtml(output.text)}</p>${forgotten}`;
  }
  if (output.shape === "summary_with_highlights") {
    const highlights = output.highlights
      .map((h) => `<li style="margin-bottom:8px;line-height:1.5;color:#333;">${escapeHtml(h)}</li>`)
      .join("");
    return `<p style="font-size:15px;line-height:1.6;color:#333;">${escapeHtml(output.summary)}</p>
<ul style="padding-left:20px;margin-top:16px;">${highlights}</ul>${forgotten}`;
  }
  const items = output.items
    .map((i) => `<li style="margin-bottom:6px;line-height:1.5;color:#333;">${escapeHtml(i)}</li>`)
    .join("");
  return `<ul style="padding-left:20px;">${items}</ul>${forgotten}`;
}

function renderText(spec: PipelineSpec, output: PipelineRunOutput): string {
  const header = `${spec.name}\n${"=".repeat(spec.name.length)}\n\n`;
  const forgotten = output.forgotten
    ? `\n\nForgotten\n${output.forgotten.title ?? "(untitled)"}${
        output.forgotten.summary ? `\n${output.forgotten.summary}` : ""
      }`
    : "";

  if (output.shape === "text") {
    return header + output.text + forgotten + "\n\n— Trove";
  }
  if (output.shape === "summary_with_highlights") {
    const bullets = output.highlights.map((h) => `- ${h}`).join("\n");
    return header + output.summary + "\n\n" + bullets + forgotten + "\n\n— Trove";
  }
  const bullets = output.items.map((i) => `- ${i}`).join("\n");
  return header + bullets + forgotten + "\n\n— Trove";
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
